//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFEFKM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int DeviceID { get; set; }
        public string DeviceName { get; set; }
        public string DeviceLocation { get; set; }
        public Nullable<int> Devicestatusid { get; set; }
    
        public virtual DeviceStatus DeviceStatu { get; set; }
    }
}
