//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFEFKM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UsersID { get; set; }
        public string UsersName { get; set; }
        public string UsersEPosta { get; set; }
        public string UsersPassword { get; set; }
        public string UsersPhone { get; set; }
        public int Userslogid { get; set; }
        public Nullable<int> Usersroleid { get; set; }
        public Nullable<int> Usersteamid { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual UsersLog UsersLog { get; set; }
        public virtual UsersRole UsersRole { get; set; }
    }
}
